### ISSUE TITLE
Implement group name restrictions

### ISSUE THREAD

**Issue by erocs** [Civcraft/NameLayer#147]
When they have been determined. Initial thoughts are 32 characters restricted to ASCII 0x21 through 0x7E.

**Comment by ProgrammerDan** [comment]
Are we concerned about people with international keyboards who might be using a different keycode set by default? 

Or just force everyone into ACSII and deal with one-offs as complaints?

**Comment by erocs** [comment]
This was a question I had on that other thread, what level of internationalization does the Minecraft client support? Keep in mind the DB table is set to latin1 so the current support is ASCII only.

**Comment by ProgrammerDan** [comment]
Well, modifying the DB table is ... relatively easy, so I'm not too worried about that. Minecraft chat supports a fair amount of internationalization, and definitely supports a lot wrt signs. I'd have to do some more research to see the exact extent of that support, but I'd expect that since it's Java based, we're just dealing with UTF-8.

**Comment by erocs** [comment]
"relatively easy" Yes, it is. I was just mentioning that the current limitations force people to ascii already.

I thought there was a character glyph sheet in the resource pack...  *shrug*  I've never looked into it.

**Comment by Maxopoly** [comment]
https://github.com/Civcraft/NameLayer/commit/f6107e33b3c8cce91b0b8b5b803d56da4e727e4b
https://github.com/Civcraft/NameLayer/commit/a07ac34b1bd412c06855152f3e1bec2bd34afbe9

**Comment by ProgrammerDan** [comment]
Nice.
