### ISSUE TITLE
Prompt Bleedthrough

### ISSUE THREAD

**Issue by ProgrammerDan** [Civcraft/NameLayer#202]
![image](https://cloud.githubusercontent.com/assets/409230/15989917/d268bb66-3053-11e6-8105-4753e7d95dd7.png)

and

![image](https://cloud.githubusercontent.com/assets/409230/15989918/dc369ef6-3053-11e6-9e08-d954cd24fc6a.png)

Basically if you "cancel" the prior prompt, the next prompt does whatever the prior prompt was asking to do...

**Comment by ProgrammerDan** [comment]
Longer first example:

![image](https://cloud.githubusercontent.com/assets/409230/15989921/fac42a50-3053-11e6-8c32-6d88b417e603.png)

**Comment by Maxopoly** [comment]
Ah yeah, nice catch. The Dialog API I made assumes you only have one dialog open at a time, but the underlying Bukkit stuff allows you to have multiple ones queued up and I forgot to close the existing one if a new one is opened.

Should be fixed by https://github.com/Civcraft/CivModCore/commit/a32702eae924b0e050b976da401f70f81fbf2d04
