### ISSUE TITLE
I want If players change their name they keep loot

### ISSUE THREAD

**Issue by zorvi** [Civcraft/NameLayer#207]
Need i download then this?

**Comment by Maxopoly** [comment]
This plugin will make it so that a players name is saved when he logs in for the first time and if he changes it later on, it wont be changed on the server. If you use an outdated plugin which identifies players based on name, then it's very likely that NameLayer will fix its problems with name changes, but I can't guarantee that. I'd recommend fixing the underlying issue in your loot plugin instead.
