### ISSUE TITLE
/help namelayer is crowded

### ISSUE THREAD

**Issue by BlackTheta** [Civcraft/NameLayer#88]
I would like to request a change to the namelayer mod. When typing "/help namelayer" all of the commands are prefaced by "This command is used to..." which takes up half of the line width. I think that starting with the verb of each command would get the point across just as well and make the /help command more useful for namelayer.

**Comment by rourke750** [comment]
If you want, you could contribute to this feature.  It isnt particularly difficult and you can even do it from notepad++.  What you would have to do is modify everyone of these classes: https://github.com/Civcraft/NameLayer/tree/master/src/vg/civcraft/mc/namelayer/command/commands and change a line here: https://github.com/Civcraft/NameLayer/blob/master/src/vg/civcraft/mc/namelayer/command/commands/AcceptInvite.java#L23 .
Then you would need to submit your code and I'll check it.  Otherwise this is low priority for me.

**Comment by drjawa** [comment]
Cutting out the boilerplate "This command is used to..." should work with
some minor edits to the rest of the sentence.

**Comment by BlackTheta** [comment]
Ok I think I sent a pull request with the changes from a fork I made. Is that how you do this?

**Comment by BlackTheta** [comment]
So that's what "close and comment" does haha

**Comment by drjawa** [comment]
https://github.com/Civcraft/NameLayer/pull/89 fixes this so closing.
